on:
  workflow_dispatch:
    inputs:
      terraform_directory:
        type: string
        default: './terraform'

jobs:

  build:
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ${{ github.event.inputs.terraform_directory }}

    runs-on: ubuntu-latest

    env:
      TF_VAR_arm_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.0
      
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
