on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform plan, apply or destroy'
        required: true
        type: choice
        options:
          - plan
          - plan-destroy
          - apply
          - destroy
        default: 'plan'
  push:
    paths:
      - './terraform/**'

jobs:

  terraform-deploy:
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: './terraform'

    runs-on: ubuntu-latest

    env:
      TF_VAR_arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2.1.1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.0
      
      - name: Terraform init
        run: |
          terraform init \
          -backend-config=storage_account_name=${{ secrets.tf_state_storage_account_name }}\
          -backend-config=container_name=${{ secrets.tf_state_storage_account_container_name}}\
          -backend-config=key=aks-lab.tfstate

      - name: Terraform plan
        if: ${{ inputs.terraform_action == 'plan' || inputs.terraform_action == 'apply' || github.event_name == 'push' }}
        run: terraform plan -out=tfplan

      - name: Terraform plan destroy
        if: ${{ inputs.terraform_action == 'plan-destroy' }}
        run: terraform plan -destroy

      - name: Terraform apply
        if: ${{ inputs.terraform_action == 'apply' }}
        run: terraform apply tfplan

      - name: Terraform destroy
        if: ${{ inputs.terraform_action == 'destroy' }}
        run: terraform destroy -auto-approve